<?php
/**
 * ArticleBenefitsServerHardwareTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  MittwaldApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Public API
 *
 * Schnittstellen für Mittwald-Kunden
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace MittwaldApi;

use PHPUnit\Framework\TestCase;

/**
 * ArticleBenefitsServerHardwareTest Class Doc Comment
 *
 * @category    Class
 * @description ArticleBenefitsServerHardware
 * @package     MittwaldApi
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ArticleBenefitsServerHardwareTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ArticleBenefitsServerHardware"
     */
    public function testArticleBenefitsServerHardware()
    {
    }

    /**
     * Test attribute "max_webspace"
     */
    public function testPropertyMaxWebspace()
    {
    }

    /**
     * Test attribute "v_cpu_units"
     */
    public function testPropertyVCpuUnits()
    {
    }

    /**
     * Test attribute "v_max_traffic"
     */
    public function testPropertyVMaxTraffic()
    {
    }

    /**
     * Test attribute "max_execution_time"
     */
    public function testPropertyMaxExecutionTime()
    {
    }

    /**
     * Test attribute "memory_limit"
     */
    public function testPropertyMemoryLimit()
    {
    }

    /**
     * Test attribute "v_max_memory"
     */
    public function testPropertyVMaxMemory()
    {
    }

    /**
     * Test attribute "v_cpu_cores"
     */
    public function testPropertyVCpuCores()
    {
    }
}
