<?php
/**
 * CreateCustomerRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  MittwaldApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Public API
 *
 * Schnittstellen für Mittwald-Kunden
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace MittwaldApi;

use PHPUnit\Framework\TestCase;

/**
 * CreateCustomerRequestTest Class Doc Comment
 *
 * @category    Class
 * @description CreateCustomerRequest
 * @package     MittwaldApi
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class CreateCustomerRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CreateCustomerRequest"
     */
    public function testCreateCustomerRequest()
    {
    }

    /**
     * Test attribute "contract_partner"
     */
    public function testPropertyContractPartner()
    {
    }

    /**
     * Test attribute "contact_person"
     */
    public function testPropertyContactPerson()
    {
    }

    /**
     * Test attribute "billing_address"
     */
    public function testPropertyBillingAddress()
    {
    }

    /**
     * Test attribute "payment_settings"
     */
    public function testPropertyPaymentSettings()
    {
    }
}
