<?php
/**
 * FormularBody2Test
 *
 * PHP version 5
 *
 * @category Class
 * @package  MittwaldApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Public API
 *
 * Schnittstellen für Mittwald-Kunden
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace MittwaldApi;

use PHPUnit\Framework\TestCase;

/**
 * FormularBody2Test Class Doc Comment
 *
 * @category    Class
 * @description FormularBody2
 * @package     MittwaldApi
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class FormularBody2Test extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "FormularBody2"
     */
    public function testFormularBody2()
    {
    }

    /**
     * Test attribute "pin_code"
     */
    public function testPropertyPinCode()
    {
    }

    /**
     * Test attribute "source_account"
     */
    public function testPropertySourceAccount()
    {
    }

    /**
     * Test attribute "source_reseller"
     */
    public function testPropertySourceReseller()
    {
    }
}
