<?php
/**
 * GuestOperatingSystemTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  MittwaldApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Public API
 *
 * Schnittstellen für Mittwald-Kunden
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.1.2
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace MittwaldApi;

/**
 * GuestOperatingSystemTest Class Doc Comment
 *
 * @category    Class
 * @description GuestOperatingSystem
 * @package     MittwaldApi
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class GuestOperatingSystemTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "GuestOperatingSystem"
     */
    public function testGuestOperatingSystem()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "identifier"
     */
    public function testPropertyIdentifier()
    {
    }

    /**
     * Test attribute "plesk_required"
     */
    public function testPropertyPleskRequired()
    {
    }

    /**
     * Test attribute "plesk_version"
     */
    public function testPropertyPleskVersion()
    {
    }
}
