<?php
/**
 * KundenApiTest
 * PHP version 7.2
 *
 * @category Class
 * @package  MittwaldApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Public API
 *
 * Schnittstellen für Mittwald-Kunden
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace MittwaldApi\Test\Api;

use \MittwaldApi\Configuration;
use \MittwaldApi\ApiException;
use \MittwaldApi\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * KundenApiTest Class Doc Comment
 *
 * @category Class
 * @package  MittwaldApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class KundenApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getBenefitDetails
     *
     * Details zu einer gebuchten Leistung.
     *
     */
    public function testGetBenefitDetails()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCurrentCustomer
     *
     * Details zu dem aktuellem Kunden.
     *
     */
    public function testGetCurrentCustomer()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCustomer
     *
     * Kundendetails auslesen.
     *
     */
    public function testGetCustomer()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCustomerBillingRecipient
     *
     * Rechungsempfänger auslesen.
     *
     */
    public function testGetCustomerBillingRecipient()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCustomerBillingSettings
     *
     * Rechungseinstellungen auslesen.
     *
     */
    public function testGetCustomerBillingSettings()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCustomerContactPerson
     *
     * Ansprechpartner auslesen.
     *
     */
    public function testGetCustomerContactPerson()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCustomerContractPartner
     *
     * Vertragspartner auslesen.
     *
     */
    public function testGetCustomerContractPartner()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCustomerPaymentSettings
     *
     * Zahlungseinstellungen auslesen.
     *
     */
    public function testGetCustomerPaymentSettings()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getInvoice
     *
     * Rechnung eines Kunden.
     *
     */
    public function testGetInvoice()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getPaymentReceipts
     *
     * Zahlungseingänge einer Rechnung.
     *
     */
    public function testGetPaymentReceipts()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listAccountsByCustomer
     *
     * Accounts eines Kunden.
     *
     */
    public function testListAccountsByCustomer()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listInvoicesByCustomer
     *
     * Rechnungen eines Kunden.
     *
     */
    public function testListInvoicesByCustomer()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for resetCustomerBillingRecipient
     *
     * Rechnungsempfänger eines Kunden zurücksetzen.
     *
     */
    public function testResetCustomerBillingRecipient()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateCustomerBillingRecipient
     *
     * Rechnungsempfänger ändern.
     *
     */
    public function testUpdateCustomerBillingRecipient()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateCustomerBillingSettings
     *
     * Rechnungseinstellungen ändern.
     *
     */
    public function testUpdateCustomerBillingSettings()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateCustomerContactPerson
     *
     * Ansprechpartner ändern.
     *
     */
    public function testUpdateCustomerContactPerson()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateCustomerContractPartner
     *
     * Vertragspartner ändern.
     *
     */
    public function testUpdateCustomerContractPartner()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateCustomerPaymentSettings
     *
     * Zahlungseinstellungen ändern.
     *
     */
    public function testUpdateCustomerPaymentSettings()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
