<?php
/**
 * VertrgeApiTest
 * PHP version 5
 *
 * @category Class
 * @package  MittwaldApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Public API
 *
 * Schnittstellen für Mittwald-Kunden
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.1.2
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace MittwaldApi;

use \MittwaldApi\Configuration;
use \MittwaldApi\ApiException;
use \MittwaldApi\ObjectSerializer;

/**
 * VertrgeApiTest Class Doc Comment
 *
 * @category Class
 * @package  MittwaldApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class VertrgeApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for cancelContract
     *
     * Kündigung einleiten.
     *
     */
    public function testCancelContract()
    {
    }

    /**
     * Test case for listCancelledContractsByCustomer
     *
     * Verträge eines Kunden, die sich aktuell im Kündigungsprozess befinden.
     *
     */
    public function testListCancelledContractsByCustomer()
    {
    }

    /**
     * Test case for listContractsByCustomer
     *
     * Verträge auslesen.
     *
     */
    public function testListContractsByCustomer()
    {
    }

    /**
     * Test case for resendCancellationConfirmation
     *
     * Kündigungsbestätigung erneut senden.
     *
     */
    public function testResendCancellationConfirmation()
    {
    }
}
