<?php
/**
 * WarenkorbApiTest
 * PHP version 7.2
 *
 * @category Class
 * @package  MittwaldApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Public API
 *
 * Schnittstellen für Mittwald-Kunden
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace MittwaldApi\Test\Api;

use \MittwaldApi\Configuration;
use \MittwaldApi\ApiException;
use \MittwaldApi\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * WarenkorbApiTest Class Doc Comment
 *
 * @category Class
 * @package  MittwaldApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class WarenkorbApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for addDomainToCart
     *
     * Warenkorb-Domainposition hinzufügen.
     *
     */
    public function testAddDomainToCart()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for addItemToCart
     *
     * Warenkorb-Position hinzufügen.
     *
     */
    public function testAddItemToCart()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for checkoutOrder
     *
     * Bestellung abschließen.
     *
     */
    public function testCheckoutOrder()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for confirmSMSVerification
     *
     * SMS-Verifizierung bestätigen.
     *
     */
    public function testConfirmSMSVerification()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createCart
     *
     * Warenkorb erstellen.
     *
     */
    public function testCreateCart()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createCartFromTemplate
     *
     * Warenkorb aus Vorlage erstellen.
     *
     */
    public function testCreateCartFromTemplate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createQuoteFromCart
     *
     * Angebot versenden.
     *
     */
    public function testCreateQuoteFromCart()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteCart
     *
     * Warenkorb löschen.
     *
     */
    public function testDeleteCart()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteItemFromCart
     *
     * Warenkorb-Position löschen.
     *
     */
    public function testDeleteItemFromCart()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCart
     *
     * Warenkorb auslesen.
     *
     */
    public function testGetCart()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for recommendCart
     *
     * Warenkorbvorlage für Account-Ausgliederung erstellen.
     *
     */
    public function testRecommendCart()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for requestSMSVerification
     *
     * SMS-Verifizierung starten.
     *
     */
    public function testRequestSMSVerification()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for shareCart
     *
     * Warenkorbvorlage erstellen.
     *
     */
    public function testShareCart()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateCart
     *
     * Warenkorb bearbeiten.
     *
     */
    public function testUpdateCart()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for verifyRecommendCart
     *
     * Überprüfe PIN-Code von Empfehlung.
     *
     */
    public function testVerifyRecommendCart()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
