<?php
/**
 * WebhooksApiTest
 * PHP version 5
 *
 * @category Class
 * @package  MittwaldApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Public API
 *
 * Schnittstellen für Mittwald-Kunden
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.1.2
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace MittwaldApi;

use \MittwaldApi\Configuration;
use \MittwaldApi\ApiException;
use \MittwaldApi\ObjectSerializer;

/**
 * WebhooksApiTest Class Doc Comment
 *
 * @category Class
 * @package  MittwaldApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class WebhooksApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createWebhook
     *
     * Registriert einen neuen Webhook.
     *
     */
    public function testCreateWebhook()
    {
    }

    /**
     * Test case for deleteWebhook
     *
     * Löscht einen Webhook.
     *
     */
    public function testDeleteWebhook()
    {
    }

    /**
     * Test case for getWebhook
     *
     * Liefert einen bestimmten Webhook.
     *
     */
    public function testGetWebhook()
    {
    }

    /**
     * Test case for listWebhooks
     *
     * Liefert alle hinterlegten Webhooks.
     *
     */
    public function testListWebhooks()
    {
    }

    /**
     * Test case for updateWebhook
     *
     * Updated den gewünschten Webhook.
     *
     */
    public function testUpdateWebhook()
    {
    }
}
